MiFragancia/MiFragancia/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MiFragancia.Models
{
    public class Producto
    {
        [Key]
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public double Precio { get; set; }
        public bool Activo { get; set; }
        public int TipoProductoId { get; set; }
        [ForeignKey("TipoProductoId ")]
        public virtual TipoProducto Tipo { get; set; }
        public int ImagenId { get; set; }
        [ForeignKey("ImagenId ")]
        public virtual Imagens Imagen { get; set; }

        public Producto()
        {

        }

    }
}

MiFragancia/MiFragancia/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiFragancia.Models;

namespace MiFragancia.Controllers
{
    public class ProductosController : Controller
    {
        private readonly FraganciaContext _context;
        public IList<Producto> carrito = new List<Producto>();
    
        public IList<Producto> select;

        public ProductosController(FraganciaContext context)
        {
            _context = context;
            if(Log.Factura == null)
                {
                Log.Factura = new List<Producto>();
            }

        }

        [HttpPost]
        public async Task<IActionResult> AddCarritoAsync(int id , int cantidad)
        {
            
            var producto = await _context.Producto
                .Include(p => p.Imagen)
                .Include(p => p.Tipo)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (producto.Cantidad >= cantidad)
            {
                if (Log.carrito == null)
                {
                    Log.carrito = new List<Producto>();
                }
                carrito.Add(producto);
                Log.cantidadProd += cantidad * producto.Precio;

                for (int i = 0; i < cantidad; i++)
                {
                    Log.carrito.Add(producto);
                }
               
                Log.Messajes = "Producto Añadido al carro";
                return RedirectToAction("Index", "Productos");

            }
            else
            {
                Log.Messajes = "Cantidad no disponible";
                return RedirectToAction("Index", "Productos");

            }
            
  
        }

        public async Task<IActionResult> Comprar(int prodRemove)
        {

            var fraganciaContext = _context.Producto.Include(p => p.Imagen).Include(p => p.Tipo);
            carrito = await fraganciaContext.ToListAsync();

            for (int i = 0; i < Log.carrito.Count; i++)
            {
                for (int j = 0; j < carrito.Count; j++)
                {
                    if (Log.carrito[i].ID == carrito[j].ID)
                    {

                        carrito[j].Cantidad -= 1;
                        _context.Update(carrito[j]);
                        await _context.SaveChangesAsync();
                        facturar(carrito[j]);

                    }
                }
                
                   
                
                

            }
            Log.carrito = new List<Producto>();
            Log.total = Log.total + Log.cantidadProd;
            Log.cantidadProd = 0;
            return RedirectToAction("Index", "Productos");
        }

        public void facturar(Producto p)
        {
            Log.Factura.Add(p);
        }



        [HttpPost]
        public async Task<IActionResult> Remove(int prodRemove)
        {
            for (int i = 0; i < Log.carrito.Count; i++)
            {
                if (Log.carrito[i].ID == prodRemove)
                {
                    Log.cantidadProd -= Log.carrito[i].Precio;
                    Log.Messajes = "Se ha eliminado el articulo " + Log.carrito[i].Nombre + " del carrito";
                    Log.carrito.Remove(Log.carrito[i]); 
                }
                
            }
            return RedirectToAction("Index", "Productos");
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
         
            var fraganciaContext = _context.Producto.Include(p => p.Imagen).Include(p => p.Tipo);

            return View(await fraganciaContext.ToListAsync());
        }

        [HttpPost]
        public async Task<Imagens> getImagen(int id)
        {
            var imagens = await _context.Imagen
            .FirstOrDefaultAsync(m => m.ID == id);

            return imagens;
        }



        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .Include(p => p.Imagen)
                .Include(p => p.Tipo)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create(object selectedDepartment = null , object selectedTipos = null)
        {

            var imagenes = from d in _context.Imagen
                                   orderby d.Nombre // Sort by name.
                                   select d;

            var tipos = from d in _context.TipoProducto
                           orderby d.Tipo // Sort by name.
                           select d;

            ViewBag.ImagenId= new SelectList(imagenes.AsNoTracking(),"ID", "Nombre", selectedDepartment);
            ViewBag.TipoProductoId = new SelectList(tipos.AsNoTracking(), "ID", "Tipo", selectedTipos);
            return View();
        }

        // POST: Productos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nombre,Descripcion,Cantidad,Precio,Activo,TipoProductoId,ImagenId")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var imagenes = from d in _context.Imagen
                           orderby d.Nombre // Sort by name.
                           select d;

            var tipos = from d in _context.TipoProducto
                        orderby d.Tipo // Sort by name.
                        select d;

            ViewBag.ImagenId = new SelectList(imagenes.AsNoTracking(), "ID", "Nombre", producto.ImagenId);
            ViewBag.TipoProductoId = new SelectList(tipos.AsNoTracking(), "ID", "Tipo", producto.TipoProductoId);

          
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            var imagenes = from d in _context.Imagen
                           orderby d.Nombre // Sort by name.
                           select d;

            var tipos = from d in _context.TipoProducto
                        orderby d.Tipo // Sort by name.
                        select d;

            ViewBag.ImagenId = new SelectList(imagenes.AsNoTracking(), "ID", "Nombre", producto.ImagenId);
            ViewBag.TipoProductoId = new SelectList(tipos.AsNoTracking(), "ID", "Tipo", producto.TipoProductoId);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nombre,Descripcion,Cantidad,Precio,Activo,TipoProductoId,ImagenId")] Producto producto)
        {
            if (id != producto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var imagenes = from d in _context.Imagen
                           orderby d.Nombre // Sort by name.
                           select d;

            var tipos = from d in _context.TipoProducto
                        orderby d.Tipo // Sort by name.
                        select d;

            ViewBag.ImagenId = new SelectList(imagenes.AsNoTracking(), "ID", "Nombre", producto.ImagenId);
            ViewBag.TipoProductoId = new SelectList(tipos.AsNoTracking(), "ID", "Tipo", producto.TipoProductoId);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .Include(p => p.Imagen)
                .Include(p => p.Tipo)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Producto.Any(e => e.ID == id);
        }
    }
}

MiFragancia/MiFragancia/Controllers/TipoProductoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiFragancia.Models;

namespace MiFragancia.Controllers
{
    public class TipoProductoesController : Controller
    {
        private readonly FraganciaContext _context;

        public TipoProductoesController(FraganciaContext context)
        {
            _context = context;
        }

        // GET: TipoProductoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.TipoProducto.ToListAsync());
        }

        // GET: TipoProductoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoProducto = await _context.TipoProducto
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tipoProducto == null)
            {
                return NotFound();
            }

            return View(tipoProducto);
        }

        // GET: TipoProductoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoProductoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Tipo,Activo")] TipoProducto tipoProducto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoProducto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoProducto);
        }

        // GET: TipoProductoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoProducto = await _context.TipoProducto.FindAsync(id);
            if (tipoProducto == null)
            {
                return NotFound();
            }
            return View(tipoProducto);
        }

        // POST: TipoProductoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Tipo,Activo")] TipoProducto tipoProducto)
        {
            if (id != tipoProducto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoProducto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoProductoExists(tipoProducto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoProducto);
        }

        // GET: TipoProductoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoProducto = await _context.TipoProducto
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tipoProducto == null)
            {
                return NotFound();
            }

            return View(tipoProducto);
        }

        // POST: TipoProductoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipoProducto = await _context.TipoProducto.FindAsync(id);
            _context.TipoProducto.Remove(tipoProducto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoProductoExists(int id)
        {
            return _context.TipoProducto.Any(e => e.ID == id);
        }
    }
}

MiFragancia/MiFragancia/Views/Productos/Create.cshtml
@model MiFragancia.Models.Producto

@{
    ViewData["Title"] = "Create";
}

@if (Log.isSingin)
{
    <h2>Create</h2>

    <h4>Producto</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cantidad" class="control-label"></label>
                    <input asp-for="Cantidad" class="form-control" />
                    <span asp-validation-for="Cantidad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label">Tipo del Prodcuto</label><br />
                    <a asp-controller="TipoProductoes" asp-action="Create">		Agregar Tipo </a>
                    <select asp-for="TipoProductoId" class="form-control" asp-items="ViewBag.TipoProductoId"></select>
                </div>
                <div class="form-group">
                    <label class="control-label">Imagen</label><br />
                    <a asp-controller="Imagens" asp-action="Create">		Añadir una imagen </a>
                    @Html.DropDownListFor(x => Model.ImagenId, (SelectList)ViewBag.ImagenId, htmlAttributes: new { @class = "form-control", id = "ImagenId" })
                    @*<select asp-for="ImagenId" class="form-control" asp-items="ViewBag.ImagenId"></select>*@
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

}
else
{
    <H1>Ooop! parece que tienes que logearte!</H1>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MiFragancia/MiFragancia/Views/Productos/Delete.cshtml
@model MiFragancia.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

@if (Log.isSingin)
{

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Producto</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cantidad)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cantidad)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Precio)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Precio)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Activo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Activo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tipo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tipo.ID)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Imagen)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Imagen.ID)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
}
else
{
    <h1>Ooops! parece que tienes que logearte!</h1>
}

MiFragancia/MiFragancia/Views/Productos/Details.cshtml
@model MiFragancia.Models.Producto

@{
    ViewData["Title"] = "Details";
}

@if (Log.isSingin)
{
    <h2>Details</h2>

    <div>
        <h4>Producto</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Cantidad)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Cantidad)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Precio)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Precio)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Activo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Activo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tipo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tipo.Tipo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Imagen)
            </dt>
            <dd>
                <img  src="~/images/@Html.DisplayFor(model => model.Imagen.ImagePath)"/>
                
            </dd>
        </dl>
    </div>
    <div>

        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>


}
else
{
    <h1>Ooops! parece que tienes que logearte!</h1>
}

MiFragancia/MiFragancia/Views/Productos/Edit.cshtml
@model MiFragancia.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

@if (Log.isSingin)
{
    <h2>Edit</h2>

    <h4>Producto</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cantidad" class="control-label"></label>
                    <input asp-for="Cantidad" class="form-control" />
                    <span asp-validation-for="Cantidad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="TipoProductoId" class="control-label"></label>
                    <select asp-for="TipoProductoId" class="form-control" asp-items="ViewBag.TipoProductoId"></select>
                    <span asp-validation-for="TipoProductoId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImagenId" class="control-label"></label>
                    <select asp-for="ImagenId" class="form-control" asp-items="ViewBag.ImagenId"></select>
                    <span asp-validation-for="ImagenId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

}
else
{
    <h1>Ooops! Parece que tienes que logearte!</h1>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}